/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja;

import java.util.logging.Level;
import java.util.logging.Logger;
import principal.CentroClinicaMedica;
import principal.Moviles;
import principal.MovilesIgualExcepcion;

/**
 *
 * @author SALA3
 */
public class IngresarMoviles extends javax.swing.JPanel {

    /**
     * Creates new form Ingresar_Moviles
     */
    public IngresarMoviles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_año = new javax.swing.JTextField();
        jTextField_Marca = new javax.swing.JTextField();
        jTextField_Modelo = new javax.swing.JTextField();
        jTextField_patente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Año :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 40, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Marca :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 50, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Modelo :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 60, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Patente :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));
        add(jTextField_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 350, 20));
        add(jTextField_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 340, 20));
        add(jTextField_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 330, 20));
        add(jTextField_patente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 330, 20));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 160, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingresar Moviles");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 910, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CentroClinicaMedica centro = new CentroClinicaMedica();
        String marca = jTextField_Marca.getText();
        String modelo = jTextField_Modelo.getText();
        String patente = jTextField_patente.getText();
        int año = Integer.parseInt(jTextField_año.getText());
        String estado = "libre";
        Moviles movil = new Moviles(marca,modelo,año,patente,estado);
        try {
            centro.Ingresar_Movil(movil, patente);
        } catch (MovilesIgualExcepcion ex) {
            
        }catch(NumberFormatException a){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField_Marca;
    private javax.swing.JTextField jTextField_Modelo;
    private javax.swing.JTextField jTextField_año;
    private javax.swing.JTextField jTextField_patente;
    // End of variables declaration//GEN-END:variables
}
