/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja;

import java.util.logging.Level;
import java.util.logging.Logger;
import principal.Afiliado_Pago_Igual_Excepcion;
import principal.Afiliados;
import principal.CentroClinicaMedica;
import principal.Pago_mes_Igual_Excepcion;
import principal.RegistroPago;

/**
 *
 * @author TAPIA
 */
public class IngresarPago extends javax.swing.JPanel {

    /**
     * Creates new form Primer_Pago
     */
    public IngresarPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_dni = new javax.swing.JTextField();
        jComboBox_mes = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField_result = new javax.swing.JTextField();
        jTextField_pago = new javax.swing.JTextField();
        jTextField_familia = new javax.swing.JTextField();
        jTextField_precio = new javax.swing.JTextField();
        jTextField_año = new javax.swing.JTextField();
        jTextField_apellido = new javax.swing.JTextField();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Numero De Familiar :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 60, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Apellido :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Documento :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Mes :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 40, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Año :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 40, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Pago :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 40, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Precio Base :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 20));
        add(jTextField_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 310, -1));

        jComboBox_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox_mes.setSelectedIndex(-1);
        add(jComboBox_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 360, -1));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 100, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Resultado :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 80, 20));

        jButton2.setText("Buscar Afiliado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 190, 20));

        jTextField_result.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_result.setEnabled(false);
        jTextField_result.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_resultKeyTyped(evt);
            }
        });
        add(jTextField_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 270, -1));

        jTextField_pago.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_pago.setEnabled(false);
        jTextField_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_pagoKeyTyped(evt);
            }
        });
        add(jTextField_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 350, -1));

        jTextField_familia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_familia.setEnabled(false);
        jTextField_familia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_familiaKeyTyped(evt);
            }
        });
        add(jTextField_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 270, -1));

        jTextField_precio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_precio.setEnabled(false);
        jTextField_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_precioKeyTyped(evt);
            }
        });
        add(jTextField_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 320, -1));

        jTextField_año.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_año.setEnabled(false);
        jTextField_año.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_añoKeyTyped(evt);
            }
        });
        add(jTextField_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 360, -1));

        jTextField_apellido.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_apellido.setEnabled(false);
        jTextField_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_apellidoKeyTyped(evt);
            }
        });
        add(jTextField_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 340, -1));

        jTextField_nombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_nombre.setEnabled(false);
        jTextField_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nombreKeyTyped(evt);
            }
        });
        add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 340, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Ingresar Pago");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 910, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        CentroClinicaMedica centro = new CentroClinicaMedica();
        String apelliado = jTextField_apellido.getText();
        int año = Integer.parseInt(jTextField_año.getText());
        int dni = Integer.parseInt(jTextField_dni.getText());
        String nombre = jTextField_apellido.getText();
        int pago;
        int precio_base = Integer.parseInt(jTextField_precio.getText());
        Afiliados afiliado = centro.Buscar_Afiliado(dni);
        int famili = afiliado.getFamilia();
        jTextField_familia.setText(String.valueOf(famili));
        String mes = String.valueOf(jComboBox_mes.getSelectedIndex());
        
        
        RegistroPago primer = new RegistroPago(nombre,apelliado,dni,año,precio_base,famili,afiliado); 
        pago = primer.pago();
        jTextField_pago.setText(String.valueOf(pago));
        
        try {
            primer.Ingresar_Mes(mes);
            centro.Registar_pago(primer, dni);
        } catch (Afiliado_Pago_Igual_Excepcion ex) {
            jTextField_result.setText("Ya existe el pago");
        }catch(NumberFormatException a){
             jTextField_result.setText("Falta Campos");
            
        } catch (Pago_mes_Igual_Excepcion ex) {
            jTextField_result.setText("Ya existe el mes de pago");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CentroClinicaMedica centro = new CentroClinicaMedica();
        int dni = Integer.parseInt(jTextField_dni.getText());
        RegistroPago nuevo = centro.Buscar_Pago(dni);
        jTextField_apellido.setText(nuevo.getNombre());
        jTextField_apellido.setText(nuevo.getApellido());
        jTextField_año.setText(String.valueOf(nuevo.getAño()));
        jTextField_familia.setText(String.valueOf(nuevo.getFam_precio()));
        jTextField_precio.setText(String.valueOf(nuevo.getPrecio_base()));
        int pago = nuevo.pago();
        jTextField_pago.setText(String.valueOf(pago));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_resultKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_resultKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_resultKeyTyped

    private void jTextField_pagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_pagoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pagoKeyTyped

    private void jTextField_familiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_familiaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_familiaKeyTyped

    private void jTextField_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_precioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_precioKeyTyped

    private void jTextField_añoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_añoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_añoKeyTyped

    private void jTextField_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_apellidoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_apellidoKeyTyped

    private void jTextField_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox_mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField_apellido;
    private javax.swing.JTextField jTextField_año;
    private javax.swing.JTextField jTextField_dni;
    private javax.swing.JTextField jTextField_familia;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_pago;
    private javax.swing.JTextField jTextField_precio;
    private javax.swing.JTextField jTextField_result;
    // End of variables declaration//GEN-END:variables
}
