/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import principal.CentroClinicaMedica;
import principal.GrupoFamiliar;
import principal.ListaVaciaExcepcion;
import principal.MovilNoExistenteExcepcion;
import principal.Moviles;
import principal.MovilesIgualExcepcion;

/**
 *
 * @author SALA3
 */
public class Modificar_Moviles extends javax.swing.JPanel {

    /**
     * Creates new form Ingresar_Moviles
     */
    public Modificar_Moviles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_año = new javax.swing.JTextField();
        jTextField_Marca = new javax.swing.JTextField();
        jTextField_Modelo = new javax.swing.JTextField();
        jTextField_patente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField_Patente = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Año :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 104, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Marca :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 104, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Modelo :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 104, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Patente :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 104, 20));
        add(jTextField_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 350, 20));
        add(jTextField_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 340, 20));
        add(jTextField_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 330, 20));
        add(jTextField_patente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 330, 20));

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 140, 20));
        add(jTextField_Patente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 320, 20));

        jButton2.setText("Buscar Movil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 140, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Matrícula :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Modificar Moviles");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 910, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CentroClinicaMedica centro = new CentroClinicaMedica();
        String marca = jTextField_Marca.getText();
        String modelo = jTextField_Modelo.getText();
        String patente = jTextField_patente.getText();
        int año = Integer.parseInt(jTextField_año.getText());
        String estado = "libre";
        Moviles movil = new Moviles(marca,modelo,año,patente,estado);
        try {
            centro.ModificarMovil(movil,patente);
            
        }catch(NumberFormatException a){
            
        } catch (ListaVaciaExcepcion ex) {
            Logger.getLogger(Modificar_Moviles.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MovilNoExistenteExcepcion ex) {
            Logger.getLogger(Modificar_Moviles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           try{
            // dni a buscar
            String patente = jTextField_Patente.getText();
            
            //asede a listas
            
            CentroClinicaMedica centro = new CentroClinicaMedica();
            
            Moviles movil= centro.BuscarMovil(patente);
            
            
            //muestra los datos   
            jTextField_Marca.setText(movil.getMarca());
            jTextField_Modelo.setText(movil.getModelo());
            jTextField_patente.setText(String.valueOf(movil.getPatente()));
            jTextField_año.setText(String.valueOf(movil.getAño()));
           

            //aca se va a realizar
           
        }catch(NumberFormatException a){
            //exepcion limpia los campos
            //aca registra campos vacios
            JOptionPane.showMessageDialog(null,"Faltan Campos ");
             jTextField_Marca.setText("");
            jTextField_Modelo.setText("");
            jTextField_patente.setText("");
            jTextField_año.setText("");
       } catch (MovilNoExistenteExcepcion ex) { 
          
            JOptionPane.showMessageDialog(null, "El movil no existe");

//  Logger.getLogger(Modificar_Moviles.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ListaVaciaExcepcion ex) {
            JOptionPane.showMessageDialog(null, "La lista esta vacia");
           
// Logger.getLogger(Modificar_Moviles.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField_Marca;
    private javax.swing.JTextField jTextField_Modelo;
    private javax.swing.JTextField jTextField_Patente;
    private javax.swing.JTextField jTextField_año;
    private javax.swing.JTextField jTextField_patente;
    // End of variables declaration//GEN-END:variables
}
