/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class jLogin extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public jLogin() {
        initComponents();
        //centra la ventana
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelMinimizar = new javax.swing.JLabel();
        jPaneliniciar = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelContraseña = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabeliniciar = new javax.swing.JLabel();
        jLabelpanel = new javax.swing.JLabel();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons_delete.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons_expand.png"))); // NOI18N
        jLabelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        jPaneliniciar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario :");
        jPaneliniciar.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));
        jPaneliniciar.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, 30));

        jLabelContraseña.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña :");
        jPaneliniciar.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 30));
        jPaneliniciar.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 30));

        jLabeliniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons_iniciar.png"))); // NOI18N
        jLabeliniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeliniciarMouseClicked(evt);
            }
        });
        jPaneliniciar.add(jLabeliniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 50, 40));

        jLabelpanel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelpanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PANEL.png"))); // NOI18N
        jPaneliniciar.add(jLabelpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 250));

        jPanel1.add(jPaneliniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 200, -1));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
       try{
           //crea una variable para la opcion
            int dialogButton = JOptionPane.YES_NO_OPTION;
            //muestra el mensaje
            int result = JOptionPane.showConfirmDialog(null,"Desea Cerrar el Systema","Salir",dialogButton);
            //pregunta si rusult == si
            if(result == 0){
                //Sale del sistema
                System.exit(0);
            } 
        //para los errores que salen
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, e);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jLabelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarMouseClicked
        this.setState(jFrame.jLogin.ICONIFIED);
        //Minimiza la ventana 
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMinimizarMouseClicked

    private void jLabeliniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeliniciarMouseClicked
        String usuario = "admin";
        String contraseña = "123";
        String pass = new String(jPasswordField.getPassword());
        String user = new String(jTextFieldUsuario.getText());
        if(user.equals(usuario) && pass.equals(contraseña)){
            jInicio acesso = new jInicio();
            acesso.setVisible(true);
            dispose();
        }else{
            JOptionPane.showConfirmDialog(this, "Usuario o Contraseña equivocada");
        }
    }//GEN-LAST:event_jLabeliniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JLabel jLabeliniciar;
    private javax.swing.JLabel jLabelpanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPaneliniciar;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
